//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soa_Form.KullaniciServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KullaniciIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Soa_Form.KullaniciServis.Kullanici[] KuListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KullaniciID {
            get {
                return this.KullaniciIDField;
            }
            set {
                if ((this.KullaniciIDField.Equals(value) != true)) {
                    this.KullaniciIDField = value;
                    this.RaisePropertyChanged("KullaniciID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Soa_Form.KullaniciServis.Kullanici[] KuList {
            get {
                return this.KuListField;
            }
            set {
                if ((object.ReferenceEquals(this.KuListField, value) != true)) {
                    this.KuListField = value;
                    this.RaisePropertyChanged("KuList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KullaniciServis.KullaniciServisSoap")]
    public interface KullaniciServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKullanici", ReplyAction="*")]
        Soa_Form.KullaniciServis.InsertKullaniciResponse InsertKullanici(Soa_Form.KullaniciServis.InsertKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.InsertKullaniciResponse> InsertKullaniciAsync(Soa_Form.KullaniciServis.InsertKullaniciRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKullanici", ReplyAction="*")]
        Soa_Form.KullaniciServis.UpdateKullaniciResponse UpdateKullanici(Soa_Form.KullaniciServis.UpdateKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.UpdateKullaniciResponse> UpdateKullaniciAsync(Soa_Form.KullaniciServis.UpdateKullaniciRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAllKullaniciResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanici", ReplyAction="*")]
        Soa_Form.KullaniciServis.SelectAllKullaniciResponse SelectAllKullanici(Soa_Form.KullaniciServis.SelectAllKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.SelectAllKullaniciResponse> SelectAllKullaniciAsync(Soa_Form.KullaniciServis.SelectAllKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKullanici", ReplyAction="*")]
        bool DeleteKullanici(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteKullaniciAsync(int id);
        
        // CODEGEN: Generating message contract since element name KullaniciIdSelectResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciIdSelect", ReplyAction="*")]
        Soa_Form.KullaniciServis.KullaniciIdSelectResponse KullaniciIdSelect(Soa_Form.KullaniciServis.KullaniciIdSelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciIdSelect", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.KullaniciIdSelectResponse> KullaniciIdSelectAsync(Soa_Form.KullaniciServis.KullaniciIdSelectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKullaniciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKullanici", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.InsertKullaniciRequestBody Body;
        
        public InsertKullaniciRequest() {
        }
        
        public InsertKullaniciRequest(Soa_Form.KullaniciServis.InsertKullaniciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKullaniciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.KullaniciServis.Kullanici entity;
        
        public InsertKullaniciRequestBody() {
        }
        
        public InsertKullaniciRequestBody(Soa_Form.KullaniciServis.Kullanici entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKullaniciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKullaniciResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.InsertKullaniciResponseBody Body;
        
        public InsertKullaniciResponse() {
        }
        
        public InsertKullaniciResponse(Soa_Form.KullaniciServis.InsertKullaniciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKullaniciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertKullaniciResult;
        
        public InsertKullaniciResponseBody() {
        }
        
        public InsertKullaniciResponseBody(bool InsertKullaniciResult) {
            this.InsertKullaniciResult = InsertKullaniciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKullaniciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateKullanici", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.UpdateKullaniciRequestBody Body;
        
        public UpdateKullaniciRequest() {
        }
        
        public UpdateKullaniciRequest(Soa_Form.KullaniciServis.UpdateKullaniciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateKullaniciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.KullaniciServis.Kullanici entity;
        
        public UpdateKullaniciRequestBody() {
        }
        
        public UpdateKullaniciRequestBody(Soa_Form.KullaniciServis.Kullanici entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKullaniciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateKullaniciResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.UpdateKullaniciResponseBody Body;
        
        public UpdateKullaniciResponse() {
        }
        
        public UpdateKullaniciResponse(Soa_Form.KullaniciServis.UpdateKullaniciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateKullaniciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateKullaniciResult;
        
        public UpdateKullaniciResponseBody() {
        }
        
        public UpdateKullaniciResponseBody(bool UpdateKullaniciResult) {
            this.UpdateKullaniciResult = UpdateKullaniciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullaniciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullanici", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.SelectAllKullaniciRequestBody Body;
        
        public SelectAllKullaniciRequest() {
        }
        
        public SelectAllKullaniciRequest(Soa_Form.KullaniciServis.SelectAllKullaniciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllKullaniciRequestBody {
        
        public SelectAllKullaniciRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullaniciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullaniciResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.SelectAllKullaniciResponseBody Body;
        
        public SelectAllKullaniciResponse() {
        }
        
        public SelectAllKullaniciResponse(Soa_Form.KullaniciServis.SelectAllKullaniciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllKullaniciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.KullaniciServis.Kullanici[] SelectAllKullaniciResult;
        
        public SelectAllKullaniciResponseBody() {
        }
        
        public SelectAllKullaniciResponseBody(Soa_Form.KullaniciServis.Kullanici[] SelectAllKullaniciResult) {
            this.SelectAllKullaniciResult = SelectAllKullaniciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciIdSelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciIdSelect", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.KullaniciIdSelectRequestBody Body;
        
        public KullaniciIdSelectRequest() {
        }
        
        public KullaniciIdSelectRequest(Soa_Form.KullaniciServis.KullaniciIdSelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciIdSelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public KullaniciIdSelectRequestBody() {
        }
        
        public KullaniciIdSelectRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciIdSelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciIdSelectResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.KullaniciServis.KullaniciIdSelectResponseBody Body;
        
        public KullaniciIdSelectResponse() {
        }
        
        public KullaniciIdSelectResponse(Soa_Form.KullaniciServis.KullaniciIdSelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciIdSelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.KullaniciServis.Kullanici KullaniciIdSelectResult;
        
        public KullaniciIdSelectResponseBody() {
        }
        
        public KullaniciIdSelectResponseBody(Soa_Form.KullaniciServis.Kullanici KullaniciIdSelectResult) {
            this.KullaniciIdSelectResult = KullaniciIdSelectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KullaniciServisSoapChannel : Soa_Form.KullaniciServis.KullaniciServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciServisSoapClient : System.ServiceModel.ClientBase<Soa_Form.KullaniciServis.KullaniciServisSoap>, Soa_Form.KullaniciServis.KullaniciServisSoap {
        
        public KullaniciServisSoapClient() {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.KullaniciServis.InsertKullaniciResponse Soa_Form.KullaniciServis.KullaniciServisSoap.InsertKullanici(Soa_Form.KullaniciServis.InsertKullaniciRequest request) {
            return base.Channel.InsertKullanici(request);
        }
        
        public bool InsertKullanici(Soa_Form.KullaniciServis.Kullanici entity) {
            Soa_Form.KullaniciServis.InsertKullaniciRequest inValue = new Soa_Form.KullaniciServis.InsertKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.InsertKullaniciRequestBody();
            inValue.Body.entity = entity;
            Soa_Form.KullaniciServis.InsertKullaniciResponse retVal = ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).InsertKullanici(inValue);
            return retVal.Body.InsertKullaniciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.InsertKullaniciResponse> Soa_Form.KullaniciServis.KullaniciServisSoap.InsertKullaniciAsync(Soa_Form.KullaniciServis.InsertKullaniciRequest request) {
            return base.Channel.InsertKullaniciAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.KullaniciServis.InsertKullaniciResponse> InsertKullaniciAsync(Soa_Form.KullaniciServis.Kullanici entity) {
            Soa_Form.KullaniciServis.InsertKullaniciRequest inValue = new Soa_Form.KullaniciServis.InsertKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.InsertKullaniciRequestBody();
            inValue.Body.entity = entity;
            return ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).InsertKullaniciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.KullaniciServis.UpdateKullaniciResponse Soa_Form.KullaniciServis.KullaniciServisSoap.UpdateKullanici(Soa_Form.KullaniciServis.UpdateKullaniciRequest request) {
            return base.Channel.UpdateKullanici(request);
        }
        
        public bool UpdateKullanici(Soa_Form.KullaniciServis.Kullanici entity) {
            Soa_Form.KullaniciServis.UpdateKullaniciRequest inValue = new Soa_Form.KullaniciServis.UpdateKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.UpdateKullaniciRequestBody();
            inValue.Body.entity = entity;
            Soa_Form.KullaniciServis.UpdateKullaniciResponse retVal = ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).UpdateKullanici(inValue);
            return retVal.Body.UpdateKullaniciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.UpdateKullaniciResponse> Soa_Form.KullaniciServis.KullaniciServisSoap.UpdateKullaniciAsync(Soa_Form.KullaniciServis.UpdateKullaniciRequest request) {
            return base.Channel.UpdateKullaniciAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.KullaniciServis.UpdateKullaniciResponse> UpdateKullaniciAsync(Soa_Form.KullaniciServis.Kullanici entity) {
            Soa_Form.KullaniciServis.UpdateKullaniciRequest inValue = new Soa_Form.KullaniciServis.UpdateKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.UpdateKullaniciRequestBody();
            inValue.Body.entity = entity;
            return ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).UpdateKullaniciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.KullaniciServis.SelectAllKullaniciResponse Soa_Form.KullaniciServis.KullaniciServisSoap.SelectAllKullanici(Soa_Form.KullaniciServis.SelectAllKullaniciRequest request) {
            return base.Channel.SelectAllKullanici(request);
        }
        
        public Soa_Form.KullaniciServis.Kullanici[] SelectAllKullanici() {
            Soa_Form.KullaniciServis.SelectAllKullaniciRequest inValue = new Soa_Form.KullaniciServis.SelectAllKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.SelectAllKullaniciRequestBody();
            Soa_Form.KullaniciServis.SelectAllKullaniciResponse retVal = ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).SelectAllKullanici(inValue);
            return retVal.Body.SelectAllKullaniciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.SelectAllKullaniciResponse> Soa_Form.KullaniciServis.KullaniciServisSoap.SelectAllKullaniciAsync(Soa_Form.KullaniciServis.SelectAllKullaniciRequest request) {
            return base.Channel.SelectAllKullaniciAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.KullaniciServis.SelectAllKullaniciResponse> SelectAllKullaniciAsync() {
            Soa_Form.KullaniciServis.SelectAllKullaniciRequest inValue = new Soa_Form.KullaniciServis.SelectAllKullaniciRequest();
            inValue.Body = new Soa_Form.KullaniciServis.SelectAllKullaniciRequestBody();
            return ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).SelectAllKullaniciAsync(inValue);
        }
        
        public bool DeleteKullanici(int id) {
            return base.Channel.DeleteKullanici(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteKullaniciAsync(int id) {
            return base.Channel.DeleteKullaniciAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.KullaniciServis.KullaniciIdSelectResponse Soa_Form.KullaniciServis.KullaniciServisSoap.KullaniciIdSelect(Soa_Form.KullaniciServis.KullaniciIdSelectRequest request) {
            return base.Channel.KullaniciIdSelect(request);
        }
        
        public Soa_Form.KullaniciServis.Kullanici KullaniciIdSelect(int id) {
            Soa_Form.KullaniciServis.KullaniciIdSelectRequest inValue = new Soa_Form.KullaniciServis.KullaniciIdSelectRequest();
            inValue.Body = new Soa_Form.KullaniciServis.KullaniciIdSelectRequestBody();
            inValue.Body.id = id;
            Soa_Form.KullaniciServis.KullaniciIdSelectResponse retVal = ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).KullaniciIdSelect(inValue);
            return retVal.Body.KullaniciIdSelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.KullaniciServis.KullaniciIdSelectResponse> Soa_Form.KullaniciServis.KullaniciServisSoap.KullaniciIdSelectAsync(Soa_Form.KullaniciServis.KullaniciIdSelectRequest request) {
            return base.Channel.KullaniciIdSelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.KullaniciServis.KullaniciIdSelectResponse> KullaniciIdSelectAsync(int id) {
            Soa_Form.KullaniciServis.KullaniciIdSelectRequest inValue = new Soa_Form.KullaniciServis.KullaniciIdSelectRequest();
            inValue.Body = new Soa_Form.KullaniciServis.KullaniciIdSelectRequestBody();
            inValue.Body.id = id;
            return ((Soa_Form.KullaniciServis.KullaniciServisSoap)(this)).KullaniciIdSelectAsync(inValue);
        }
    }
}
