//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soa_Form.SirketServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SirketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdresField;
        
        private int AracSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Soa_Form.SirketServis.Sirket[] sirListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((this.SirketIDField.Equals(value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SirketAd {
            get {
                return this.SirketAdField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdField, value) != true)) {
                    this.SirketAdField = value;
                    this.RaisePropertyChanged("SirketAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SirketAdres {
            get {
                return this.SirketAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdresField, value) != true)) {
                    this.SirketAdresField = value;
                    this.RaisePropertyChanged("SirketAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AracSayisi {
            get {
                return this.AracSayisiField;
            }
            set {
                if ((this.AracSayisiField.Equals(value) != true)) {
                    this.AracSayisiField = value;
                    this.RaisePropertyChanged("AracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Soa_Form.SirketServis.Sirket[] sirList {
            get {
                return this.sirListField;
            }
            set {
                if ((object.ReferenceEquals(this.sirListField, value) != true)) {
                    this.sirListField = value;
                    this.RaisePropertyChanged("sirList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SirketServis.SirketServisSoap")]
    public interface SirketServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSirket", ReplyAction="*")]
        Soa_Form.SirketServis.InsertSirketResponse InsertSirket(Soa_Form.SirketServis.InsertSirketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSirket", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.SirketServis.InsertSirketResponse> InsertSirketAsync(Soa_Form.SirketServis.InsertSirketRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAllSirketResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllSirket", ReplyAction="*")]
        Soa_Form.SirketServis.SelectAllSirketResponse SelectAllSirket(Soa_Form.SirketServis.SelectAllSirketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllSirket", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.SirketServis.SelectAllSirketResponse> SelectAllSirketAsync(Soa_Form.SirketServis.SelectAllSirketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSirketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSirket", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.SirketServis.InsertSirketRequestBody Body;
        
        public InsertSirketRequest() {
        }
        
        public InsertSirketRequest(Soa_Form.SirketServis.InsertSirketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSirketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.SirketServis.Sirket entity;
        
        public InsertSirketRequestBody() {
        }
        
        public InsertSirketRequestBody(Soa_Form.SirketServis.Sirket entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSirketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSirketResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.SirketServis.InsertSirketResponseBody Body;
        
        public InsertSirketResponse() {
        }
        
        public InsertSirketResponse(Soa_Form.SirketServis.InsertSirketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSirketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertSirketResult;
        
        public InsertSirketResponseBody() {
        }
        
        public InsertSirketResponseBody(bool InsertSirketResult) {
            this.InsertSirketResult = InsertSirketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllSirketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllSirket", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.SirketServis.SelectAllSirketRequestBody Body;
        
        public SelectAllSirketRequest() {
        }
        
        public SelectAllSirketRequest(Soa_Form.SirketServis.SelectAllSirketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllSirketRequestBody {
        
        public SelectAllSirketRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllSirketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllSirketResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.SirketServis.SelectAllSirketResponseBody Body;
        
        public SelectAllSirketResponse() {
        }
        
        public SelectAllSirketResponse(Soa_Form.SirketServis.SelectAllSirketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllSirketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.SirketServis.Sirket[] SelectAllSirketResult;
        
        public SelectAllSirketResponseBody() {
        }
        
        public SelectAllSirketResponseBody(Soa_Form.SirketServis.Sirket[] SelectAllSirketResult) {
            this.SelectAllSirketResult = SelectAllSirketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SirketServisSoapChannel : Soa_Form.SirketServis.SirketServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SirketServisSoapClient : System.ServiceModel.ClientBase<Soa_Form.SirketServis.SirketServisSoap>, Soa_Form.SirketServis.SirketServisSoap {
        
        public SirketServisSoapClient() {
        }
        
        public SirketServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SirketServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirketServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirketServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.SirketServis.InsertSirketResponse Soa_Form.SirketServis.SirketServisSoap.InsertSirket(Soa_Form.SirketServis.InsertSirketRequest request) {
            return base.Channel.InsertSirket(request);
        }
        
        public bool InsertSirket(Soa_Form.SirketServis.Sirket entity) {
            Soa_Form.SirketServis.InsertSirketRequest inValue = new Soa_Form.SirketServis.InsertSirketRequest();
            inValue.Body = new Soa_Form.SirketServis.InsertSirketRequestBody();
            inValue.Body.entity = entity;
            Soa_Form.SirketServis.InsertSirketResponse retVal = ((Soa_Form.SirketServis.SirketServisSoap)(this)).InsertSirket(inValue);
            return retVal.Body.InsertSirketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.SirketServis.InsertSirketResponse> Soa_Form.SirketServis.SirketServisSoap.InsertSirketAsync(Soa_Form.SirketServis.InsertSirketRequest request) {
            return base.Channel.InsertSirketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.SirketServis.InsertSirketResponse> InsertSirketAsync(Soa_Form.SirketServis.Sirket entity) {
            Soa_Form.SirketServis.InsertSirketRequest inValue = new Soa_Form.SirketServis.InsertSirketRequest();
            inValue.Body = new Soa_Form.SirketServis.InsertSirketRequestBody();
            inValue.Body.entity = entity;
            return ((Soa_Form.SirketServis.SirketServisSoap)(this)).InsertSirketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.SirketServis.SelectAllSirketResponse Soa_Form.SirketServis.SirketServisSoap.SelectAllSirket(Soa_Form.SirketServis.SelectAllSirketRequest request) {
            return base.Channel.SelectAllSirket(request);
        }
        
        public Soa_Form.SirketServis.Sirket[] SelectAllSirket() {
            Soa_Form.SirketServis.SelectAllSirketRequest inValue = new Soa_Form.SirketServis.SelectAllSirketRequest();
            inValue.Body = new Soa_Form.SirketServis.SelectAllSirketRequestBody();
            Soa_Form.SirketServis.SelectAllSirketResponse retVal = ((Soa_Form.SirketServis.SirketServisSoap)(this)).SelectAllSirket(inValue);
            return retVal.Body.SelectAllSirketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.SirketServis.SelectAllSirketResponse> Soa_Form.SirketServis.SirketServisSoap.SelectAllSirketAsync(Soa_Form.SirketServis.SelectAllSirketRequest request) {
            return base.Channel.SelectAllSirketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.SirketServis.SelectAllSirketResponse> SelectAllSirketAsync() {
            Soa_Form.SirketServis.SelectAllSirketRequest inValue = new Soa_Form.SirketServis.SelectAllSirketRequest();
            inValue.Body = new Soa_Form.SirketServis.SelectAllSirketRequestBody();
            return ((Soa_Form.SirketServis.SirketServisSoap)(this)).SelectAllSirketAsync(inValue);
        }
    }
}
