//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOAProjeEntities2 : DbContext
    {
        public SOAProjeEntities2()
            : base("name=SOAProjeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araba> Araba { get; set; }
        public virtual DbSet<KiralamaBilgi> KiralamaBilgi { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
