//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soa_Form.ArabaServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araba", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Araba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracMarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlakaField;
        
        private int EhliyetYasiField;
        
        private int YasSiniriField;
        
        private int GunkukSinirKilometreField;
        
        private int AnlikKilometreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AirbagField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private int KiralamaBedeliField;
        
        private int SirketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Soa_Form.ArabaServis.Araba[] AraListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracID {
            get {
                return this.AracIDField;
            }
            set {
                if ((this.AracIDField.Equals(value) != true)) {
                    this.AracIDField = value;
                    this.RaisePropertyChanged("AracID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AracMarka {
            get {
                return this.AracMarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.AracMarkaField, value) != true)) {
                    this.AracMarkaField = value;
                    this.RaisePropertyChanged("AracMarka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AracModel {
            get {
                return this.AracModelField;
            }
            set {
                if ((object.ReferenceEquals(this.AracModelField, value) != true)) {
                    this.AracModelField = value;
                    this.RaisePropertyChanged("AracModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plaka {
            get {
                return this.PlakaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlakaField, value) != true)) {
                    this.PlakaField = value;
                    this.RaisePropertyChanged("Plaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int YasSiniri {
            get {
                return this.YasSiniriField;
            }
            set {
                if ((this.YasSiniriField.Equals(value) != true)) {
                    this.YasSiniriField = value;
                    this.RaisePropertyChanged("YasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GunkukSinirKilometre {
            get {
                return this.GunkukSinirKilometreField;
            }
            set {
                if ((this.GunkukSinirKilometreField.Equals(value) != true)) {
                    this.GunkukSinirKilometreField = value;
                    this.RaisePropertyChanged("GunkukSinirKilometre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AnlikKilometre {
            get {
                return this.AnlikKilometreField;
            }
            set {
                if ((this.AnlikKilometreField.Equals(value) != true)) {
                    this.AnlikKilometreField = value;
                    this.RaisePropertyChanged("AnlikKilometre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((object.ReferenceEquals(this.AirbagField, value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int KiralamaBedeli {
            get {
                return this.KiralamaBedeliField;
            }
            set {
                if ((this.KiralamaBedeliField.Equals(value) != true)) {
                    this.KiralamaBedeliField = value;
                    this.RaisePropertyChanged("KiralamaBedeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Sirket {
            get {
                return this.SirketField;
            }
            set {
                if ((this.SirketField.Equals(value) != true)) {
                    this.SirketField = value;
                    this.RaisePropertyChanged("Sirket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Resim {
            get {
                return this.ResimField;
            }
            set {
                if ((object.ReferenceEquals(this.ResimField, value) != true)) {
                    this.ResimField = value;
                    this.RaisePropertyChanged("Resim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public Soa_Form.ArabaServis.Araba[] AraList {
            get {
                return this.AraListField;
            }
            set {
                if ((object.ReferenceEquals(this.AraListField, value) != true)) {
                    this.AraListField = value;
                    this.RaisePropertyChanged("AraList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArabaServis.ArabaServisSoap")]
    public interface ArabaServisSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAraba", ReplyAction="*")]
        Soa_Form.ArabaServis.InsertArabaResponse InsertAraba(Soa_Form.ArabaServis.InsertArabaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAraba", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.ArabaServis.InsertArabaResponse> InsertArabaAsync(Soa_Form.ArabaServis.InsertArabaRequest request);
        
        // CODEGEN: Generating message contract since element name SelectAllArabaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllAraba", ReplyAction="*")]
        Soa_Form.ArabaServis.SelectAllArabaResponse SelectAllAraba(Soa_Form.ArabaServis.SelectAllArabaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllAraba", ReplyAction="*")]
        System.Threading.Tasks.Task<Soa_Form.ArabaServis.SelectAllArabaResponse> SelectAllArabaAsync(Soa_Form.ArabaServis.SelectAllArabaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArabaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAraba", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.ArabaServis.InsertArabaRequestBody Body;
        
        public InsertArabaRequest() {
        }
        
        public InsertArabaRequest(Soa_Form.ArabaServis.InsertArabaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArabaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.ArabaServis.Araba entity;
        
        public InsertArabaRequestBody() {
        }
        
        public InsertArabaRequestBody(Soa_Form.ArabaServis.Araba entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArabaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArabaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.ArabaServis.InsertArabaResponseBody Body;
        
        public InsertArabaResponse() {
        }
        
        public InsertArabaResponse(Soa_Form.ArabaServis.InsertArabaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArabaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertArabaResult;
        
        public InsertArabaResponseBody() {
        }
        
        public InsertArabaResponseBody(bool InsertArabaResult) {
            this.InsertArabaResult = InsertArabaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllArabaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllAraba", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.ArabaServis.SelectAllArabaRequestBody Body;
        
        public SelectAllArabaRequest() {
        }
        
        public SelectAllArabaRequest(Soa_Form.ArabaServis.SelectAllArabaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllArabaRequestBody {
        
        public SelectAllArabaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllArabaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllArabaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soa_Form.ArabaServis.SelectAllArabaResponseBody Body;
        
        public SelectAllArabaResponse() {
        }
        
        public SelectAllArabaResponse(Soa_Form.ArabaServis.SelectAllArabaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllArabaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soa_Form.ArabaServis.Araba[] SelectAllArabaResult;
        
        public SelectAllArabaResponseBody() {
        }
        
        public SelectAllArabaResponseBody(Soa_Form.ArabaServis.Araba[] SelectAllArabaResult) {
            this.SelectAllArabaResult = SelectAllArabaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArabaServisSoapChannel : Soa_Form.ArabaServis.ArabaServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArabaServisSoapClient : System.ServiceModel.ClientBase<Soa_Form.ArabaServis.ArabaServisSoap>, Soa_Form.ArabaServis.ArabaServisSoap {
        
        public ArabaServisSoapClient() {
        }
        
        public ArabaServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArabaServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArabaServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArabaServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.ArabaServis.InsertArabaResponse Soa_Form.ArabaServis.ArabaServisSoap.InsertAraba(Soa_Form.ArabaServis.InsertArabaRequest request) {
            return base.Channel.InsertAraba(request);
        }
        
        public bool InsertAraba(Soa_Form.ArabaServis.Araba entity) {
            Soa_Form.ArabaServis.InsertArabaRequest inValue = new Soa_Form.ArabaServis.InsertArabaRequest();
            inValue.Body = new Soa_Form.ArabaServis.InsertArabaRequestBody();
            inValue.Body.entity = entity;
            Soa_Form.ArabaServis.InsertArabaResponse retVal = ((Soa_Form.ArabaServis.ArabaServisSoap)(this)).InsertAraba(inValue);
            return retVal.Body.InsertArabaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.ArabaServis.InsertArabaResponse> Soa_Form.ArabaServis.ArabaServisSoap.InsertArabaAsync(Soa_Form.ArabaServis.InsertArabaRequest request) {
            return base.Channel.InsertArabaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.ArabaServis.InsertArabaResponse> InsertArabaAsync(Soa_Form.ArabaServis.Araba entity) {
            Soa_Form.ArabaServis.InsertArabaRequest inValue = new Soa_Form.ArabaServis.InsertArabaRequest();
            inValue.Body = new Soa_Form.ArabaServis.InsertArabaRequestBody();
            inValue.Body.entity = entity;
            return ((Soa_Form.ArabaServis.ArabaServisSoap)(this)).InsertArabaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soa_Form.ArabaServis.SelectAllArabaResponse Soa_Form.ArabaServis.ArabaServisSoap.SelectAllAraba(Soa_Form.ArabaServis.SelectAllArabaRequest request) {
            return base.Channel.SelectAllAraba(request);
        }
        
        public Soa_Form.ArabaServis.Araba[] SelectAllAraba() {
            Soa_Form.ArabaServis.SelectAllArabaRequest inValue = new Soa_Form.ArabaServis.SelectAllArabaRequest();
            inValue.Body = new Soa_Form.ArabaServis.SelectAllArabaRequestBody();
            Soa_Form.ArabaServis.SelectAllArabaResponse retVal = ((Soa_Form.ArabaServis.ArabaServisSoap)(this)).SelectAllAraba(inValue);
            return retVal.Body.SelectAllArabaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soa_Form.ArabaServis.SelectAllArabaResponse> Soa_Form.ArabaServis.ArabaServisSoap.SelectAllArabaAsync(Soa_Form.ArabaServis.SelectAllArabaRequest request) {
            return base.Channel.SelectAllArabaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soa_Form.ArabaServis.SelectAllArabaResponse> SelectAllArabaAsync() {
            Soa_Form.ArabaServis.SelectAllArabaRequest inValue = new Soa_Form.ArabaServis.SelectAllArabaRequest();
            inValue.Body = new Soa_Form.ArabaServis.SelectAllArabaRequestBody();
            return ((Soa_Form.ArabaServis.ArabaServisSoap)(this)).SelectAllArabaAsync(inValue);
        }
    }
}
