//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araba()
        {
            this.KiralamaBilgi = new HashSet<KiralamaBilgi>();
        }
    
        public int AracID { get; set; }
        public string AracMarka { get; set; }
        public string AracModel { get; set; }
        public string Plaka { get; set; }
        public Nullable<int> EhliyetYasi { get; set; }
        public Nullable<int> YasSiniri { get; set; }
        public Nullable<int> GunlukSinirKilometre { get; set; }
        public Nullable<int> AnlikKilometre { get; set; }
        public string Airbag { get; set; }
        public Nullable<int> BagajHacmi { get; set; }
        public Nullable<int> KoltukSayisi { get; set; }
        public Nullable<int> KiralamaBedeli { get; set; }
        public Nullable<int> Sirket { get; set; }
        public string Resim { get; set; }
        public string Durum { get; set; }
    
        public virtual Sirket Sirket1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralamaBilgi> KiralamaBilgi { get; set; }
    }
}
